title: synthv-dictionaries
description: Interlingual user dictionary of Synthesizer V.
remote_theme: just-the-docs/just-the-docs

url: https://just-the-docs.github.io

aux_links:
  View on Github: https://github.com/Slidingwall/synthv-dictionaries/
